### ISSUE TITLE
Getting error with watershed function in data_cleaning

### ISSUE THREAD

**Issue by ronocara** [aronnicksnts/MURA-Classification#2]
tried it in main.ipynb getting an error of:

`error: OpenCV(4.6.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<1>; VDepth = cv::impl::{anonymous}::Set<0, 2, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'`

But adaptive_image function works well and implemented it in the input image

**Comment by aronnicksnts** [comment]
fixed
